# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true
        
tools:
    external_code_coverage: true
    
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
