language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

allow_failures:
  - php: hhvm
  - php: nightly

install:
  - composer self-update
  - composer update --prefer-dist

before_script:
  - phpenv config-rm opcache.ini
  - phpenv config-rm xdebug.ini
  - composer install

script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/
