language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

allow_failures:
  - php: hhvm
  - php: nightly
  
install:
- php composer.phar install --dev --no-interaction --prefer-source

before_script:
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/
