language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

allow_failures:
  - php: hhvm
  - php: nightly
  
before_install:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update
  
install:
  - composer update --prefer-dist

before_script:
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/
