language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

allow_failures:
  - php: hhvm
  - php: nightly
  
install:
  - composer self-update
  - composer --version
  - composer install
  - composer update --prefer-dist

before_script:
  - phpenv config-rm xdebug.ini
  - php --version

script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/
  
