language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

allow_failures:
  - php: hhvm
  - php: nightly

before_script:
  - composer self-update
  - composer update --prefer-dist
  - composer install

script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/