language: php
php:
  - 5.5
  - 5.6

allow_failures:
  - php: hhvm
  - php: nightly
  
install:
  - composer self-update
  - composer --version
  - composer install
  - composer update --prefer-dist
  - travis/setup-php-extensions.sh

before_script:
  - ./configure --disable-opcache
  - phpenv config-rm xdebug.ini
  - php --version

script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/
  
