language: php
php:
  - 5.5
  - 5.6
  - nightly

addons:
  code_climate:
    repo_token: 850707f5b5d621b8149d6f95e05a1abe356be323b90ebc24edd51f3bf40da14c

install:
  - composer self-update
  - composer --version
  - composer install
  - composer update --prefer-dist

before_script:
  - chmod +x travis/setup-php-extensions.sh
  - travis/setup-php-extensions.sh
  - php --version

script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/


