language: php

php:
  - 5.5
  - 5.6
  - nightly

install:
  - composer self-update
  - composer --version
  - composer install --prefer-source

before_script:
  - chmod +x travis/setup-php-extensions.sh
  - travis/setup-php-extensions.sh
  - php --version
  - php -m

script:
  - mkdir tmp
  - if [[ ${TRAVIS_PHP_VERSION} != "nightly" ]]; then vendor/bin/phpunit --coverage-clover tmp/clover.xml --bootstrap ./tests/bootstrap.php tests/; ./vendor/bin/test-reporter --coverage-report tmp/clover.xml; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "nightly" ]]; then vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/; fi

