language: php
php:
- 5.5
- 5.6
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq libssh2-1-dev libssh2-php
- pecl install -f ssh2-beta < .noninteractive
install:
- composer self-update
- composer --version
- composer install --prefer-source
before_script:
- chmod +x travis/setup-php-extensions.sh
- travis/setup-php-extensions.sh
- php --version
- php -m
script:
- mkdir tmp
- if [[ ${TRAVIS_PHP_VERSION} != "nightly" ]]; then vendor/bin/phpunit --coverage-clover
  tmp/clover.xml --bootstrap ./tests/bootstrap.php tests/; ./vendor/bin/test-reporter
  --coverage-report tmp/clover.xml; fi
- if [[ ${TRAVIS_PHP_VERSION} == "nightly" ]]; then vendor/bin/phpunit --bootstrap
  ./tests/bootstrap.php tests/; fi
after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover tmp/clover.xml
notifications:
  slack:
    rooms:
      secure: EP5oiPmHRXLKNDwcS6BrTeN7Oe3DPax8dmqSTFM97yS+eDnu5wBqmvjitMP1JYtzPse8LQWG0vxcW4d9GlNsx8TIFcPrbX1JWu1bkjt95o7ifo2sVOxLrb3vLfPsjJBnv4Cgo1240kRAdh6RDOjzjP9mZ3d1JMPN29xQaGGclL/8PI5rJWCB4t342uydhqlvbo3D+qiM8VuDE+7LtYDg98j0phRjDJbEA5dr3BjgLiHDxdGko7QJzg3aW/0YuszZeetivDQQ0uHF8rdn4T1Ox50EQXvuARgZeR5iNd72vCJZUefRfnHb6HLmJ1ydkhdCyWA5/Sb4YUSoOvec0DrzFcsZn9MuRVctmgk7tcV+yzMSZQJWjAiDTAqSa07HjrJ1CXUBhJOeiL0eYWaA25kuHluJnQxeBxL6Deyx7I2hhXDEO7A/Xcmkf6NA296za+T8z4cAfzxNbOtL5chforLvX5W4Lt3ElZ7lvdmM3Hwz/8uLvWVJWdYsV4XpfpWx0bEIIMSiTJcvkckHER+zAKw7mRfczwk88rE6Qqsf78Mlif/gV8fbChzzhEiThiNzcPsxr4/A/yXNSk5Vb6MPCIQ1yn2uD+oGZkK6RKShEzIOL9hIH9yv9ulNXtWF/OfIkVvkuNybSj8qfqUqPmXKC9QDT1yXGPqFJVp12B/8eLJrQaQ=
