language: php
php:
  - 5.5
  - 5.6
  - nightly

addons:
  code_climate:
    repo_token: 850707f5b5d621b8149d6f95e05a1abe356be323b90ebc24edd51f3bf40da14c

install:
  - composer self-update
  - composer --version
  - composer install --prefer-source

before_script:
  - chmod +x travis/setup-php-extensions.sh
  - travis/setup-php-extensions.sh
  - php --version

script:
  - vendor/bin/phpunit --coverage-clover /tmp/clover.xml --bootstrap ./tests/bootstrap.php tests/
  - export CODECLIMATE_REPO_TOKEN=850707f5b5d621b8149d6f95e05a1abe356be323b90ebc24edd51f3bf40da14c
  - ./vendor/bin/test-reporter --coverage-report /tmp/clover.xml

