language: php
php:
  - 5.5
  - 5.6
  - nightly

install:
  - composer self-update
  - composer --version
  - composer install
  - composer update --prefer-dist

before_script:
  - chmod +x travis/setup-php-extensions.sh
  - travis/setup-php-extensions.sh
  - php --version

script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  
after_script:
 - chmod +x ./codeclimate.sh
 - ./codeclimate.sh